[package]
name = "hoang/combat-testing"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Wire = "elentium/wire@0.0.4"
DataService = "leifstout/dataservice@1.0.0"
